### ISSUE TITLE
stuck whren

### ISSUE THREAD

**Issue by longxianlin** [swiftsocket/SwiftSocket#12]
client.read(1024*10)  stuck because server didn't close the socket connection!
how to solve it in client side?

**Comment by danshevluk** [comment]
`client.read(1024*10)` will try to read 1024*10 bytes forever. 
If read will receive less bytes that it should, it will wait until timeout. By default timeout is forever. You can specify timeout like that:
```swift
client.read(1024*10, timeout: 10) // 10 second timeout
```
