### ISSUE TITLE
How to read all lines

### ISSUE THREAD

**Issue by Clever91** [swiftsocket/SwiftSocket#17]
Hi,  My problem is socket read only (1024*10) charaters. how to read all lines in swift 2 ?

My code: 
private func sendRequest(data: String, client: TCPClient?) -> (String?) {
    // It use ufter connection
    if client != nil {
        // Send data  (WE MUST ADD TO SENDING MESSAGE '\n' )
        let (isSuccess, errorMessage) = client!.send(str: "\(data)\n")
        if isSuccess {
            // Read response data
            let data = client!.read(1024*10)
            if let d = data {
                // Create String from response data
                if let str = NSString(bytes: d, length: d.count, encoding: NSUTF8StringEncoding) as? String {
                    return (data: str)
                } else {
                    return (data: nil)
                }
            } else {
                return (data: nil)
            }
        } else {
            print(errorMessage)
            return (data: nil)
        }
    } else {
        return (data: nil)
    }
}

and other question is here :http://stackoverflow.com/questions/34036070/how-to-read-all-lines-in-socket-swift

**Comment by aixinlove** [comment]
you should put read method in a loop. here is an [example](https://github.com/swiftsocket/WebpageDownload/blob/master/WebpageDownload/ViewController.swift)

**Comment by aixinlove** [comment]
@Clever91 
you should put read method in a loop. here is an [example](https://github.com/swiftsocket/WebpageDownload/blob/master/WebpageDownload/ViewController.swift)

**Comment by Clever91** [comment]
Thanks answer, i have another question. how to check socket ( like isConnect() ) ? Is ti possible ? If possible, give me example.

**Comment by Clever91** [comment]
and this example get error: 
fatal error: unexpectedly found nil while unwrapping an Optional value
how to stop while loop ? I don't understand ( i am new in swift ).

**Comment by Clever91** [comment]
I fixed this like ( some code changed)
while true {
                    let data=self.client!.read(1024*10)
                    if data == nil {
                        break
                    }
                    dispatch_async(dispatch_get_main_queue(), { () -> Void in
                        //print("Data: \(String(bytes: data!, encoding: NSUTF8StringEncoding)!)")
                        
                        self.sourceCodeView.text=self.sourceCodeView.text+String(bytes: data!, encoding: NSUTF8StringEncoding)!
                    })
                }
Is it true ?
