### ISSUE TITLE
How do I receive a response from a UDP packet?

### ISSUE THREAD

**Issue by prem111as** [swiftsocket/SwiftSocket#170]
Hi. Im have a problem. When you try to receive a response to a UDP packet, the connection will be suspended. 

Code:

    private func sendRequest(string: String, using client: UDPClient) -> String? {

        
        switch client.send(string: string) {
     
        case .success:

           let(byteArray, senderIPAddress, senderPort) = client.recv(1024)
           if let byteArray = byteArray,
            let string = String(data: Data(byteArray), encoding: .utf8)
           {
            print(string)
           }
            
        case .failure(_): break
          
        }
        return nil
    }

Please help!

**Comment by devyhia** [comment]
@prem111as  Have you found a solution to this problem?
