### ISSUE TITLE
how to check socket

### ISSUE THREAD

**Issue by Clever91** [swiftsocket/SwiftSocket#18]
this library worked perfect but i need check socket is connacted not not. How to check socket ? Is it possibale ? Please, advise me. thanks !

**Comment by Clever91** [comment]
I didn't find anywhere ( I am new in swift socket)

**Comment by indrajitsinh** [comment]
hey plz help me to setup this library

**Comment by Clever91** [comment]
@indrajitsinh, hi. okey what is problam to set up socket library ?

**Comment by Clever91** [comment]
and I found my question's answer, if you have any question swift or objective c, ask me here..

**Comment by lynxerzhang** [comment]
@Clever91 how to check socket is connect or not ?

**Comment by irineu** [comment]
Please post your solution for us.

**Comment by Clever91** [comment]
import Foundation

class SocketManager {
    
    let socket : TCPClient
    
    class var sharedInstance: SocketManager {
        struct Singleton {
            static let instance = SocketManager()
        }
        return Singleton.instance
    }
    
    init() {
        // Create the socket
        self.socket = TCPClient(addr: "0.0.0.0", port: xx)
        
    }
    
    internal func onConnect()->Bool {
        // Connect the socket
        let (success, msg ) = self.socket.connect(timeout: 1)
        print("Socket \(msg) ( \(success))")
        return success
    }
    
    internal func isConnected()->Bool {
        // Connect the socket
        let (success, msg ) = self.socket.isConnact()
        print("\(msg) ( \(success))")
        return success
    }
    
    internal func closeSocket()->Bool {
        let (success, msg ) = self.socket.close()
        print("Socket is closed: \(msg)")
        return success
    }
    
    internal func sendMessage(message: String, handler: (response: String)-> Void) {
        
//        let qualityOfServiceClass = QOS_CLASS_BACKGROUND
//        let backgroundQueue = dispatch_get_global_queue(qualityOfServiceClass, 0)
//        dispatch_async(backgroundQueue, {
        
        let response = self.sendRequest(message, client: self.socket)
        
        var bytes: [UInt8] = []
        // We must DELETE '\n'
        if response != nil {
            let responseData = response!.stringByReplacingOccurrencesOfString("\n", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
            bytes = Converter.hexstringConvertToBytes(responseData)
        }
            
        let url = UrlManager(json: "")
        
        if !bytes.isEmpty {
            handler(response: url.decodeResponseData(bytes))
        } else {
            handler(response: "")
        }
//            dispatch_async(dispatch_get_main_queue(), { () -> Void in
//                //print("This is run on the main queue")
//            })
//            
//        })
    }
    
    private func sendRequest(data: String, client: TCPClient?) -> (String?) {
        
        var allLines: String = ""
        // It use ufter connection
        if client != nil {
            // Send data  (WE MUST ADD TO SENDING MESSAGE '\n' )
            let (isSuccess, errorMessage) = client!.send(str: "\(data)\n")
            if isSuccess {
                var stop = String()
                repeat {
                    stop = ""
                    // Read response data
                    let data = client!.read(1024*100000)
                    if let d = data {
                        // Create String from response data
                        if let str = NSString(bytes: d, length: d.count, encoding: NSUTF8StringEncoding) as? String {
                            allLines = allLines + str
                            stop = str
                        } else {
                            return (data: nil)
                        }
                    } else {
                        return (data: nil)
                    }
                } while stop.length == 1188
                return (data: allLines)
                
            } else {
                print(errorMessage)
                return (data: nil)
            }
        } else {
            return (data: nil)
        }
    }
}

**Comment by Clever91** [comment]
`self.socket.isConnact()` this method is not socket library but i have changed socket library

**Comment by jl2378** [comment]
@Clever91 What did you do to implement `self.socket.isConnact()`

**Comment by OmarBizreh** [comment]
When I use 

`self.socket = TCPClient(addr: "0.0.0.0", port: xx)`

No matter which IP I use (even from outside my subnet) if I call `socket.connect(timeout: 5)`
it says connection succeeded. I don't understand how is this possible?

**Comment by KushThakkar** [comment]
Need Demo APP For this (SWIFT).
Any one help?

**Comment by danshevluk** [comment]
@KushThakkar you can check out `iOS Example folder` in the repo

**Comment by XXIrene** [comment]
@Clever91 Could you please post how did you write the socket.isConnact() method?
