### ISSUE TITLE
How to send response to client from udp server

### ISSUE THREAD

**Issue by akshit5230** [swiftsocket/SwiftSocket#182]
Hello. There is no send method for a UDPServer object of this pod so how do i respond to the client which sent me data?

**Comment by RanguraN** [comment]
> Hello. There is no send method for a UDPServer object of this pod so how do i respond to the client which sent me data?

Hello! Tell me how you send a broadcast request to the udp server?
I installed a udp client with address "255.255.255.255" and port 3333.
Is this the right decision?

**Comment by Asshasahole** [comment]
> Hello. There is no send method for a UDPServer object of this pod so how do i respond to the client which sent me data?

Same question.

**Comment by akshit5230** [comment]
I wasted so much time on this pod and then just gave up and switched to the CocoaAsyncSocket pod. It does everything you need.
