### ISSUE TITLE
Anybody has swiftSocket working as a Nativescript plugin?

### ISSUE THREAD

**Issue by growerp** [swiftsocket/SwiftSocket#189]
I am not an IOS developer, but i need to be able to write to an ESCPOS printer. swift socket should be able to do this, however i could not yet get his to work as a nativescript plugin.
My question: anybody already done  this?  I saw  Aandrea Cremisini working on it, however no workable plugin is available under hit github account

if it helps i can show you the plugin i got so far...

Thanks for your help in advance...

**Comment by toams69** [comment]
Hi growerp,

I have the same need. 
Did you worked on that?
I am not neither an IOS developper..

**Comment by growerp** [comment]
yes finally got the ESCPOS printer working at: https://www.npmjs.com/package/nativescript-escpos-printer
Regards
