### ISSUE TITLE
How to enable SSL/ TLS security?

### ISSUE THREAD

**Issue by RizITN** [swiftsocket/SwiftSocket#22]
I'm using your socket class in one of my project and it is working fine for un-secure connection. Now we want to use secure connection so I need to know how can we achieve this. So my questions are:
1. How can we enable SSL/ TLS security check before making connection?
2. How can I attache a (.pfx / .p12) certificate for authentication? 

Please reply ASAP.

**Comment by aixinlove** [comment]
sorry, we are not support ssl/tls

**Comment by simonhessner** [comment]
Are there any plans to support TLS in the future?
