### ISSUE TITLE
Passing return data from Byte Array to a string Swift 2.2 (Broken + FIX)

### ISSUE THREAD

**Issue by horendus** [swiftsocket/SwiftSocket#32]
I recently have used your library and found your method to convert return data byte arrays to strongs is no longer working with Swift because **String.stringWithBytes** is not longer part of the String class.

**This is your example which no longer works**

`var data = client.read(1024*10)`
     `if let d = data {`
         `if let str = String.stringWithBytes(d, length: d.count, encoding: NSUTF8StringEncoding){`
       `println(str)`
         `}`

**My Change / Fix suggestion**
`let data = client.read(1024*10)`
         `if data != nil {`
            `str = NSString(bytes: data!, length: data!.count, encoding: NSUTF8StringEncoding)`
               `println(str)`
          `}`

To display the returned data (NSString) in a text box I used casting
`textBox.text = String(str)`

or in one call you can use
`textBox.text = String(NSString(bytes: data!, length: data!.count, encoding: NSUTF8StringEncoding))`

I tried to make a pull request but I couldn't work out how it worked (sorry im still learning how GitHub works) 

Hope this helps someone as it had be caught up for quite some time!

**Comment by danshevluk** [comment]
Hey! You can check my Swift 3.0 solution there on the similar issue #43
