### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by thddaniel** [swiftsocket/SwiftSocket#33]
When I add the ysocket.framework and build, it shows the error " clang: error: linker command failed with exit code 1 (use -v to see invocation)". How can I solve this? thank you

**Comment by danshevluk** [comment]
Hello there! Is this issue still occurs? You can try latest release and hopefully it will be OK 👍

**Comment by danshevluk** [comment]
I'll close this issue for now. Feel free to reopen it!
