### ISSUE TITLE
I'm only seeing response header

### ISSUE THREAD

**Issue by jigzat** [swiftsocket/SwiftSocket#4]
Thank you for this, I apologize if this is obvious but I'm only seeing the response header and not the actual response from the server. I'm just using the posted example and printing the response into a UILabel. The response is plain text.

I'm prototyping something and this library is very useful.

UPDATE:

Sorry I mistyped client.read(1024*10) I had some other number inside.

UPDATE 2: 

it keeps happening, sometimes returns the headers only and not the data.

**Comment by xyyc** [comment]
@jigzat  please parse your code here, i will check for you.

**Comment by jigzat** [comment]
...       
        self.idLabel = UILabel(frame: CGRect(x:0,y:0,width:self.topView.frame.size.width,height:200))
        self.idLabel?.backgroundColor = UIColor.grayColor()
        self.idLabel?.numberOfLines = 10
        self.topView.addSubview(self.idLabel!)
...

func requestService()
    {
        var client:TCPClient = TCPClient(addr: "www.bucle.co", port: 80)
        var (success,errmsg)=client.connect(timeout: 2)
        
        if success{
            var (success,errmsg)=client.send(str:"GET /announce HTTP/1.0\n\n" )
            if success{
                var data=client.read(1024*10)
                if let d=data{
                    if let str = String(bytes: d, encoding: NSUTF8StringEncoding){
                        self.idLabel?.text = str
                    }
                }
            }else{
                self.idLabel?.text = errmsg
            }
        }else{
            self.idLabel?.text = errmsg
        }
}

**Comment by sjmadsen** [comment]
You're probably having the same problem as #49. The underlying `read()` socket call doesn't guarantee that it will return everything. A blocking socket will block on `read()` until at least one byte is available, and it will return up to the specified number of bytes, but if less is available at the time of the call, it will return less than you can accept.
