### ISSUE TITLE
converting read data back to a string

### ISSUE THREAD

**Issue by OliverMardle** [swiftsocket/SwiftSocket#43]
Hi, I have sent a string to my iOS app which delivers fine, the string is "26" however the iOS app interprets it as [50, 54]. How do I convert this back into a string? I am reading it as let data = client.read(1024).

Thanks

**Comment by danshevluk** [comment]
Hey! 

Here is the code:
```swift
let bytes: [Byte] = [50, 54] // Byte is a typealias for UInt8
let stringData = Data(bytes: bytes)
let string = String(data: stringData, encoding: .utf8) // "26"
```
