### ISSUE TITLE
No TcpClient FUNCTION

### ISSUE THREAD

**Issue by JohnsonChow** [swiftsocket/SwiftSocket#46]
import SwiftSocket
And then use the  TCPClient() function
you can see the error  'not found'

**Comment by danshevluk** [comment]
Hello there! 

There is no constructor without parameters for `TCPClient` class. `TCPClient` doesn't make sense without socket info. You should use `init(address: String, port: Int32)`. 

Example:

```swift
let client = TCPClient(address: "apple.com", port: 80)
```

**Comment by JohnsonChow** [comment]
3Q
