### ISSUE TITLE
TCPClient.read() does not read everything

### ISSUE THREAD

**Issue by jpaffrath** [swiftsocket/SwiftSocket#49]
I use TCPClient.read() to read responses from a mpd server.
The server itself sends more than, e.g. 2048 Bytes but I only receive 1448 Bytes:

```Swift
if let responseData = self.client.read(self.DATALEN) {
            print("Len: \(responseData.count)")
            response = String.init(bytes: responseData, encoding: String.Encoding.utf8)
}
```

**Comment by danshevluk** [comment]
Are you sure that you server actually sends you more bytes?

**Comment by jpaffrath** [comment]
Yes, I tested it with netcat.
The server sends more than 1448 Bytes.

**Comment by jpaffrath** [comment]
I tested with several other Swift Socket Libraries and I always get the same result: Only 1448 Bytes are being read.
May this be an error in the underlying implementation?

**Comment by danshevluk** [comment]
ok, so if `self.DATALEN` in your example is actually equals to 2048, than problem is in the underlying implementation. I'm using `SwiftSocket` in my own project an everything works fine. I will check if there are more than 1448 in any response.

**Comment by jpaffrath** [comment]
Thank you!

**Comment by jpaffrath** [comment]
Update:
When I invoke `client.read(self.DATALEN)`, only 1448 Bytes are being read. After a second `client.read(self.DATALEN)`, the remaining bytes are read, too.

That means `client.read` does not read the whole DATALEN and the other bytes are dangling until another `client.read` fetches them.

**Comment by qhu91it** [comment]
I have problem too, client.read(1024*10) only read first 1448 Bytes.
In debug, I set a breakpoint in this line and hit Step Over then all data read ok.

**Comment by danshevluk** [comment]
This is weird... I googled "1448 socket" and looks like problem somewhere in C code. There is a problem with packages size or something like that.

**Comment by sjmadsen** [comment]
This is just the way that socket reads work. From the `read(2)` manpage:

>`read()` attempts to read `nbyte` bytes of data from the object referenced by the descriptor `fildes` into the buffer pointed to by `buf`.

>Upon successful completion, `read()`, `readv()`, and `pread()` return the number of bytes actually read and placed in the buffer.  The system guarantees to read the number of bytes requested if the descriptor references a normal file that has that many bytes left before the end-of-file, but in no other case.

When the (TCP) server writes out more data than will fit in an Ethernet frame, your networking stack breaks the write up into segments. As these segments are received by the client, the kernel makes the data available for reading by the application.

Your `read()` is getting the data available at the time of the call, but it will not wait (block) for more. 1448 is very close to the size of a typical Ethernet MTU of 1500, minus the 20 byte IP header and 20 byte TCP header. Perhaps your TCP is using options (which will make its header larger) or your MTU is slightly smaller than 1500.

Anyway, this is normal behavior. If your application layer expects a certain amount of data, it must make multiple calls to `read()` and gather the data before doing something with it.
