### ISSUE TITLE
SwiftSocket Compatible with Swift 2.3

### ISSUE THREAD

**Issue by gupinheiro** [swiftsocket/SwiftSocket#52]
Hi guys,

Is there some version of SwiftSocket compatible with Swift 2.3? 
Thanks

**Comment by danshevluk** [comment]
There is no an easy way to find in history a commit with 2.3 support.
Release tags were used only after migrating to Swift 3.0. I suggest you to create your own fork and migrate code to swift 2.3. It should not be that hard. Also, you should think about migrating your project to 3.0. Promise you, it's worth it 🎉
