### ISSUE TITLE
converting code to Swift3

### ISSUE THREAD

**Issue by yagilc** [swiftsocket/SwiftSocket#53]
Hi,

I'm trying to move to Swift3 and I'm getting error on the following line:

if let addr = String(CString: buff, encoding: String.Encoding.utf8){ //Error here *
                tcpClient.addr=addr
            }

* the error: Argument labels(Cstring:,ecoding) do not match any available overloads

Thanks

**Comment by danshevluk** [comment]
Hey! What is the type of `buff`?

**Comment by danshevluk** [comment]
Hey! Looks like the error is in name of the first parameter:
```swift
if let addr = String(cString: buff, encoding: .utf8) {
    tcpClient.addr = addr
}
```

**Comment by yagilc** [comment]
thanks,

Yagil
