### ISSUE TITLE
Execution Order Error

### ISSUE THREAD

**Issue by gupinheiro** [swiftsocket/SwiftSocket#54]
Hi,

I have developed a class derived from TCPClient to implement some write/read operations with a TCP server on a PLC. The actions I'm intended in perform are: 
1) Send a command (write) requisition and read requisition confirmation -> var(success,statusMessage,command) = Client.WriteCommand(CommandValue); 
2) Request some PLCs value(write) and read the values from PLC (read)->
var(success,statusMessage,data1,data2,data3) = Client.ReadData();

When I execute each action in distinct button actions it works perfectly, but when I use them into one action at the sequence:
     var(success,statusMessage,command) = Client.WriteCommand(CommandValue);
     var(success,statusMessage,data1,data2,data3) = Client.ReadData();                      
it seems the processes doesn't wait until the first line execution and try to execute the second one. It make mess in my protocol communication. Do you know if this lack of synchrony could be solved?

Thanks

**Comment by danshevluk** [comment]
Hello there! 

I guess, that you implementation can  `WriteCommand` and `ReadData`cause this issue, but they are no part of SwiftSocket codebase. Can you reproduce this issue using only TCPClient methods and provide your code sample?

**Comment by gupinheiro** [comment]
Here is the implementation:
import Foundation

func toByteArray<T>(var value: T) -> [UInt8] {
    return withUnsafePointer(&value) {
        Array(UnsafeBufferPointer(start: UnsafePointer<UInt8>($0), count: sizeof(T)))
    }
}

func fromByteArray<T>(value: [UInt8], _: T.Type) -> T {
    return value.withUnsafeBufferPointer {
        return UnsafePointer<T>($0.baseAddress).memory
    }
}


public class iPadClient {
   
    var client:TCPClient
    var connected: Bool
    
    
    public init() {
        self.client = TCPClient(address:"",port:502)
        self.connected = false
    }
    
    
    public func Desconnect()->(Bool,String){
        
        if self.connected{
            var(success,errorMsg) = cliente.close()
            if success{
                self.connected = false
            }
            
            return(success,errorMsg)
            
        }else{
            
            return(true,"Client is already desconnected.")
        }
        
        
    }

    
    public func Connect(IPServidor:String)->(Bool,String){
        
        self.connected = false
        
        if IPServidor.isEmpty == false{
            
            self.client = TCPClient(address: IPServidor, port: 502)
            
            if self.client.fd != 0 {
                var(success,error) = cliente.connect(30)
                
                if success{
            
                    self.connected = true
                    return (true,"Connection with server on \(IPServidor) done.")
                }else {
                   return (success,error)
                }
            }else{
                return (false,"Error to create socket client TCP.")
            }
        }else{
            return (false,"IP invalid.")
        }
        
    }
    
    
    public func writeCommand(Command:Int16)->(Bool,String,Int16){
        
        var IP,IP2:Int32
        var Erro,Operation,CRC, Command2:Int16
        var data:[UInt8]
        
        if self.connected{
            
            Operation = 2
            IP = 9987
            CRC = calcCRC(toByteArray(IP)+toByteArray(Operation)+toByteArray(Command))
            
            var (success,errorMsg)=cliente.send(toByteArray(IP)+toByteArray(Operation)+toByteArray(Command)+toByteArray(CRC))
            if success{
                
                var answear:[UInt8]!=cliente.read(1024*10)//, timeout:200)
                
                data = [UInt8](answear[0...3])
                IP2 = fromByteArray(data, Int32.self)
                data = [UInt8](answear[4...5])
                Operation = fromByteArray(data, Int16.self)
                data = [UInt8](answear[6...7])
                Erro = fromByteArray(data, Int16.self)
                data = [UInt8](answear[8...9])
                Command2 = fromByteArray(data, Int16.self)
                data = [UInt8](answear[10...11])
                CRC = fromByteArray(data, Int16.self)
                
                if CRC == calcCRC(answear){
                    if Erro == 0{
                        if IP == IP2{
                            if Command == Command2{
                                return(true,"Command write done.", Command2)
                    
                            }else{ return(false,"Command write inconsistent.",0) }
                            
                        }else{ return(false,"Server answear was not for this client.",0) }
                    
                    }else{ return (false, "Command write inconsistent.",0) }
                    
                }else{ return (false, "Message corrupted.",0) }
                
            }else {return (false,errorMsg,0)}
            
        } else{ return(false,"Socket client isn't connected to a server.",0) }
    
      
    }
    
    
    public func writeWatchdog(Wacthdog:Int16)->(Bool,String,Int16){
        
        var IP,IP2:Int32
        var Erro,Operation,CRC, Wacthdog2:Int16
        var data:[UInt8]
        
        if self.connected{
            
            Operation = 2
            IP = 9987
            CRC = calcCRC(toByteArray(IP)+toByteArray(Operation)+toByteArray(Wacthdog))
            
            var (success,errorMsg) = self.client.send(toByteArray(IP)+toByteArray(Operation)+toByteArray(Wacthdog)+toByteArray(CRC))
            if success{
                
                var answear:[UInt8]!=self.client.read(1024*10)//, timeout:200)
                
                data = [UInt8](answear[0...3])
                IP2 = fromByteArray(data, Int32.self)
                data = [UInt8](answear[4...5])
                Operation = fromByteArray(data, Int16.self)
                data = [UInt8](answear[6...7])
                Erro = fromByteArray(data, Int16.self)
                data = [UInt8](answear[8...9])
                Wacthdog2 = fromByteArray(data, Int16.self)
                data = [UInt8](answear[10...11])
                CRC = fromByteArray(data, Int16.self)
                
                if CRC == calcCRC(answear){
                    if Erro == 0{
                        if IP == IP2{
                            return(true,"Escrita de wacthdog done.",Wacthdog2)
                            
                        }else{ return(false,"Server answear was not for this client.",0) }
                        
                    }else{ return (false, "Command write inconsistent.",0) }
                    
                }else{ return (false, "Message corrupted.",0) }
                
            }else {return (false,errorMsg,0)}
            
        } else{ return(false,"Socket client isn't connected to a server.",0) }
        
        
    }
    
    
    public func leituradata() -> (Bool,String,Float,Float,Int16){
        
        var IP,IP2:Int32
        var Erro,Operation,CRC, Estado:Int16
        var data:[UInt8]
        var Volume, Encerrante:Float
        
        if self.connected{
            
            Operation = 1
            IP = 9987
            CRC = calcCRC(toByteArray(IP)+toByteArray(Operation))
            
            var (success,errorMsg)=self.client.send(toByteArray(IP)+toByteArray(Operation)+toByteArray(CRC))
            
            if success{
                
                var answear:[UInt8]!=self.client.read(1024*10)//, timeout:200)
                 
                data = [UInt8](answear[0...3])
                IP2 = fromByteArray(data, Int32.self)
                data = [UInt8](answear[4...5])
                Operation = fromByteArray(data, Int16.self)
                data = [UInt8](answear[6...7])
                Erro = fromByteArray(data, Int16.self)
                data = [UInt8](answear[8...11])
                Encerrante = fromByteArray(data, Float.self)
                data = [UInt8](answear[12...15])
                Volume = fromByteArray(data, Float.self)
                data = [UInt8](answear[16...17])
                Estado = fromByteArray(data, Int16.self)
                data = [UInt8](answear[18...19])
                CRC = fromByteArray(data, Int16.self)
                
                if CRC == calcCRC(answear){
                    if Erro == 0{
                        if IP == IP2{
                            
                            return(true,"Data read done.", Encerrante, Volume,Estado)
                        }else{
                            return(false,"Server answear was not for this client.",0,0,0)
                        }
                    
                    }else{
                        return (false, "Data inconsistent.", 0, 0, 0)
                    }
                    
                }else{
                    return (false, "Message corrupted.", 0, 0, 0)
                }
                
            }else{
                return (false, errorMsg, 0, 0, 0)
            }
            
        }else{
            return(false,"Socket client isn't connected to a server.",0,0,0)
        }
        
    }
}

----------------------
Function on button trigger:
   iPadClient1 = iPadClient()
    var result:Bool = false
    var(flag,statusMessage) =  iPadClient1.Connect("192.168.1.1")
    
    
    if flag{
        
        var(success,statusMessage,estado) = ClienteiPad.writeCommand(Int16(4))
        
        if success{
        
            let alert1 = UIAlertView()
            alert1.title = "Attention!"
            alert1.message = "Write done. Estatus: \(estado)"
            alert1.addButtonWithTitle("OK")
            alert1.show()

            var(success2,statusMessage2,Encerrante,Volume,Estado) = ClienteiPad.readData()
            
            if success2{
                let alert = UIAlertView()
                alert.title = "Attention"
                alert.message = "Read done!"
                alert.addButtonWithTitle("OK")
                alert.show()
                if Estado & Int16(16) == 16 {
                    result = true
                }
            }else{
                let alert3 = UIAlertView()
                alert3.title = "Attention"
                alert3.message = statusMessage
                alert3.addButtonWithTitle("OK")
                alert3.show()
            }
    
        }else{
            let alert4 = UIAlertView()
            alert4.title = "Attention!"
            alert4.message = statusMessage
            alert4.addButtonWithTitle("OK")
            alert4.show()
        }
    }
    
    ClienteiPad.Desconnect ()
    return result
    
    
}


As you can see I simply added some protocol coding for my application, but the main function on communication is provided by SwiftSocket. When I try to execute the code above it seems that the send socket operation on readData function it's executed before the read socket operation on writeCommand and as a result the server TCP became fuzzy, and the client became stuck in the last read socket operation.

Thanks.

**Comment by danshevluk** [comment]
I'm sorry to tell you that but your code is pretty hard to read... 😰
First of all, is suggest you to update SwiftSocket to the latest version. You can do it with Cocoapods or Carthage.
Then try to remove application logic from sockets code to try to understand the problem. 
I noticed that you are using `self.client.read(1024*10)` to read from socket and actually using only 20 of those bytes. So, it's good idea to use `client.read(20)`. Reading more bytes can cause you issue.

**Comment by gupinheiro** [comment]
I'm sorry, but I need to develop this in swift 2.3, because client will not update to swift 3.0. About read operation, do you think the quantity of required byte to read could be the issue? I'll change it as you suggested.

**Comment by gupinheiro** [comment]
Just one more question. When the read socket operation will finish: after timeout? after read the byte quantity required? Another one, in my case, I basically try to do send, read, send, read operations in that sequence. Could the second send operation start even if the previous read isn't over?

**Comment by danshevluk** [comment]
When we are talking about one client send operations cannot send asynchronously. Read operation should finish after timeout, or when all bytes are read.

**Comment by gupinheiro** [comment]
Hi danshevluk,

It seems the problem above is because I was trying communicate in simulation mode, when I deployed the app on iPad it works. Now I have another question, I need to develop a server TCP that will listen the client requisitions in background, it doesn't have to deadlock the application, could you give a hint?

**Comment by danshevluk** [comment]
@gupinheiro if you want to do something in Swift and not lock main thread you should create a background queue and do it there:
```swift
let queueToDoSomething = DispatchQueue(label: "super.awesome.queue", qos: .background)

queueToDoSomething.async {
   // do something
}
```

You should just read about dispatch queues. they are cool 🎉
