### ISSUE TITLE
Not compatible with OS X?

### ISSUE THREAD

**Issue by DominikPalo** [swiftsocket/SwiftSocket#55]
I'm trying to add `SwiftSocket` to my project (OS X app) using the Cocoapods, but `pod install` fails with an error: 

> [!] The platform of the target `my-app-name` (OS X 10.11) is not compatible with `SwiftSocket (1.2)`, which does not support `osx`.

**Comment by danshevluk** [comment]
Hey! `SwiftSocket` is compatible with macOS apps with deployment target 10.10 and up. What version of `SwiftSocket` did you try?

**Comment by DominikPalo** [comment]
I didn't specified a specific version of  `SwiftScosket` - I simply added a line `pod 'SwiftSocket'` to my `Podfile` and the used `pod install` command to install it, but it failed with described error. I'm using the latest version of pod.

**Comment by danshevluk** [comment]
Did you specify platform and deployment target in your Podfile? Here is an example:
```ruby
platform :osx, '10.11'

target 'awesome-app-name' do
  use_frameworks!

  pod 'SwiftSocket'

end
```

**Comment by DominikPalo** [comment]
No, my `Podfile`:
```
use_frameworks!

target 'my-app-name' do
    pod 'ObjectMapper', '~> 2.2'
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftSocket'
end
```

But other packages (ObjectMapper and Alamofire) are working without problems

**Comment by danshevluk** [comment]
I tried to do the same, then googled a bit... so I don't know for now what can cause this issue. Looks like specifying platform in `Podfile` fixes that.
(btw I think that it's actually a good idea to set a deployment target for each platform in your `Podfile`)

**Comment by danshevluk** [comment]
UPD: I think that default deployment target for `:osx` in Cocoapods is lower than 10.10

**Comment by danshevluk** [comment]
Yeah! It's actually true! Default deployment for macOS in Cocoapods is 10.8 ([source](
https://github.com/CocoaPods/CocoaPods/blob/32e84e15cab49ead0c61ce85c2324acf9c4f72f9/lib/cocoapods/generator/copy_resources_script.rb#L51)). You have to specify default deployment target for your platform to make it work. Just add following to your `Podfile`: 

```ruby 
platform :osx, '10.11`
```
