### ISSUE TITLE
Hex String

### ISSUE THREAD

**Issue by ArifADS** [swiftsocket/SwiftSocket#57]
I'm trying to send a command to an esc/pos, in Javascript, the command would be something like this

`PAPER_CUT_A     : '\x1d\x56\x41'` but swift do not accept those escape sequences.

I tried something like `client.send(data: [0x1d,0x56,0x41])` but that doesn't work either, is there any other way?

**Comment by danshevluk** [comment]
If you want to send bytes you have to wrap them in `Data` first:
```swift
let bytesArray: [UInt8] = [0x1d, 0x56, 0x41]
client.send(data: Data(bytes: bytesArray))
```
