### ISSUE TITLE
Support for Swift 2.3

### ISSUE THREAD

**Issue by nneuberger1** [swiftsocket/SwiftSocket#58]
Is there a branch or tag available to support Swift 2.3?

Were having other secondary issues with our projects migrating to Swift 3 and looking at alternatives to using this library, but with Swift 2.3.

Is this possible?

**Comment by danshevluk** [comment]
Unfortunately there is no available tags or branches. You can look up earlier commits to find version 2.2. Like this one: https://github.com/swiftsocket/SwiftSocket/commit/7cdf0b8284bddc3948587a5cdd843cacc61a2943

Also you can try to find someone's fork with 2.3 support. 

Good luck!

**Comment by nneuberger1** [comment]
Alrighty Thanks for the help!  I'll report back if I have luck with it and report back for documentation purposes.
