### ISSUE TITLE
Trouble with OS X

### ISSUE THREAD

**Issue by kimaldis** [swiftsocket/SwiftSocket#62]
I've installed SwiftSocket using CocoaPods but it won't compile for OS X. I've included OS X version in the Podfile, 10.12:

     static var Sender = TCPClient(address: "127.0.0.1", port: 8080 )

_Error is 'use of unresolved identifier TCPClient._

any thoughts appreciated.

**Comment by kimaldis** [comment]
import SwiftSocket

Doh!

sorry.

**Comment by danshevluk** [comment]
Yay! 🎉
