### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by RafaelPlantard** [swiftsocket/SwiftSocket#63]
Is there any date to release a version with support to SPM?

**Comment by danshevluk** [comment]
We have plans to do that but right now I can't tell you any particular date. I'll let you know 🎉

**Comment by RafaelPlantard** [comment]
Thanks @danshevluk I will wait for it.

**Comment by qhua948** [comment]
Any news on this?

**Comment by hulk10425** [comment]
Thanks @danshevluk

**Comment by marzvrover** [comment]
This is addressed in PR #207
