### ISSUE TITLE
Swift 2?

### ISSUE THREAD

**Issue by vahids** [swiftsocket/SwiftSocket#65]
Hi, I'm implementing a library that needs a TCP server socket.
apple document dose not complete:
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/UsingSocketsandSocketStreams.html

So I found your library, but seems like It's just support Swift > 3
I just need to run a TCP Socket server on a port to connect other device to this port.
sorry for my english ;-)

**Comment by danshevluk** [comment]
If you need only server is suggest you to look at this library: 
https://github.com/httpswift/swifter
It's a good HTTP server in Swift with a lot of options and I suppose have a tag with Swift 2 support.

If you want to use SwiftSocket you read similar issue: https://github.com/swiftsocket/SwiftSocket/issues/58

We do not support Swift 2. 

Hope it's helpful 🙂
