### ISSUE TITLE
Help - developing an IoT app

### ISSUE THREAD

**Issue by gupinheiro** [swiftsocket/SwiftSocket#66]
HI I'm trying to build some app on IoT using swift sockets. iPad will be client and it will send requisitions (for read tags and write commands) for industrial assets and I have some questions, could you help me?
- I need to use delimiters in my messages or just fix size can guarantee messages could be read correctly?
- Is it reasonable to polling read tags periodically and only write commands when necessary? In this approach how you suggest to do this operations and acess data read?
- In case of fail? I just need to descart read and do another read? 
Thanks

**Comment by danshevluk** [comment]
1) Fixed size should be fine. Also you can write message size before every request message. For example every 4 bytes in every message will be its size.
2) I do not quite understand your question
3) You should set timeout for read and try another again when it fails.

**Comment by gupinheiro** [comment]
Thanks,
I was talking about how to implement read as a background task that will be running while the app is runing, something like a driver communication. Do you know how I can do this? Thanks.

**Comment by danshevluk** [comment]
You can create readingQueue and run there reading loop:
```swift
import Foundation
import SwiftSocket

let readingQueue = DispatchQueue(label: "com.swiftsocket.reading-queue")

func startReadingQueue(for client: TCPClient) {
  var readingWorkItem: DispatchWorkItem?
  
  readingWorkItem = DispatchWorkItem {
    guard let item = readingWorkItem else { return }
    
    while !item.isCancelled {
      // Read 4 byte message
      guard let message = client.read(4, timeout: 1) else { continue }
     
      // do something with message
    }
  }
  readingQueue.async(execute: readingWorkItem!)
}

```

The trick with `DispatchWorkItem` allows you stop reading queue. You should store `readingQueue` somewhere and call `readingWorkItem.cancel()` when needed.

**Comment by gupinheiro** [comment]
Thanks,
Don't you have an Swift 2 example? Client doesn't want to update to swift 3 for now

**Comment by danshevluk** [comment]
No, I don't. I'm not sure that `DispatchWorkItem` is available in Swift 2, but you can do the same thing with `NSOperation`

**Comment by gupinheiro** [comment]
How?

**Comment by danshevluk** [comment]
Here is a tutorial:
https://www.raywenderlich.com/76341/use-nsoperation-nsoperationqueue-swift
