### ISSUE TITLE
server socket example

### ISSUE THREAD

**Issue by DynamicBit** [swiftsocket/SwiftSocket#7]
hi,
I have a problem with your "server socket excample". Iam starting the server on my Macbook and trying to connect with a telnet client running on a virtual machine (ubuntu). the error message is this: "telnet: Unable to connect to remote host: Connection refused". Any idea to solve the problem?

**Comment by xyyc** [comment]
@DynamicBit you should change the server ip address from "127.0.0.1" to your local ip address
