### ISSUE TITLE
Is there any way to respond to incoming messages without polling?

### ISSUE THREAD

**Issue by fishtrousers** [swiftsocket/SwiftSocket#70]
I am writing a client app and messages can appear from the server at any time. Is there a way of setting up a method that will be called when messages appear? I don't want to have to call read() repeatedly to see if there's anything received.

Cool library, btw, I got everything else to work very easily.

**Comment by danshevluk** [comment]
You can create a specific queue for reading and run there `DispatchWorkItem` with infinite loop:
```swift
var readingWorkItem: DispatchWorkItem?

readingWorkItem = DispatchWorkItem { [weak self] in
  guard let item = readingWorkItem else { return }

  while !item.isCancelled {
    // Read 4 bytes message
    guard let bytes = client.read(4, timeout: -1) else {
      print("Continue reading")
      continue
    }

    // do your stuff
  }
}
```

**Comment by fishtrousers** [comment]
Thanks for the quick response and apologies for not noticing that you'd already answered this.
Everything is working now

**Comment by Lulli4444** [comment]
Can you please explain this to me? I don't understand how to make it work.

**Comment by fishtrousers** [comment]
This is what I did:

	//---------------------------------------------------------------------
	//	This queue runs in the background and polls for incoming characters
	//---------------------------------------------------------------------
	func startReadingQueue(for client: TCPClient) {
  
 		readingWorkItem = DispatchWorkItem {
			guard let item = self.readingWorkItem else { return }
	
			// read incoming characters one at a time and add to message
			while !item.isCancelled {
				guard let d = client.read(1, timeout: 1) else { continue }

				let c = String(bytes: d, encoding: .utf8)
				self.message += c!

				if (c == "\n") {		// '\n'
					self.HandleMessage()
				}
			}
		}
		readingQueue.async(execute: readingWorkItem!)
	}

I call this function just after I successfully open the tcp port. It runs in the background collecting incoming characters. In my app, incoming messages are terminated with '\n' so when '\n' turns up I call HandleMessage.

**Comment by Lulli4444** [comment]
Thank you very much!

**Comment by SNThunderbolt** [comment]
hi @fishtrousers ,
is there a way to do this for ump as well?
reading messages in the background?

**Comment by fishtrousers** [comment]
What is ump?

**Comment by SNThunderbolt** [comment]
@fishtrousers I'm sorry I misspelled. I meant UDP

**Comment by SNThunderbolt** [comment]
I just do anything to make this peace of code work for the ump but couldn't.
I have a server which I want to register to via udp command of "REGISTER:username"

here I the function:

    func register(username: String) -> (Bool, String) {
        //registering a user
        var udpString : String = "REGISTER:\(username)"

        var output = false
        var result = client.send(string: udpString)
        var response = ""

        if result.isSuccess {
            readingWorkItem1 = DispatchWorkItem {
                guard let item = self.readingWorkItem1 else { return }

                // read incoming msges one at a time and add to message
                while !item.isCancelled {
                    print("hi")
                    let (serverResponse, _, _) = self.client.recv(32)
                    print("this is it \(serverResponse)")
                    if (serverResponse == nil) {
                        print("closing")
                        continue
                    } else {
                        //guard let (d, _, _) = (client.recv(32)) else { continue }
                       // item.cancel()
                        print("hello again")
                        for i in 1...serverResponse!.count {
                            self.newMsg.append(Character(UnicodeScalar(serverResponse![i-1])))
                            print ("The Server Response To {REGISTER} is \(response)")
                            if response == "OK" {
                                output = true
                            } else {
                                output = false
                            }
                        }
                    }
                    print("continusing!")
                }
            }
            DispatchQueue.global().async(execute: readingWorkItem1!)
        } else {
            print ("result unsucessful.")
        }
        client.close()
        return (output, response)
    }

**Comment by SNThunderbolt** [comment]
when I run the above code, even when the server responds "OK", my code stuck in an infinite loop.

**Comment by fishtrousers** [comment]
Hi,

I’ve only ever written one Swift program and it was a long time ago so I don’t think I can help you much. I’ve never written anything for UDP. All I remember from the one I wrote is that you need two threads - one to listen for incoming messages and another to run the main program. 

Sorry I can’t be more helpful!

**Comment by SNThunderbolt** [comment]
@fishtrousers Ok thank you for your time pal  :)

**Comment by PrashantKT** [comment]
Is there any way to listen continuously  on some event ? just like socket.io socket.on("status update") ?
