### ISSUE TITLE
UDPClient

### ISSUE THREAD

**Issue by R2D6233** [swiftsocket/SwiftSocket#79]
Guys. Help please write such a program for UDP.
```swift
class ViewController: UIViewController {
  
  @IBOutlet weak var textView: UITextView!
  
  let host = "apple.com"
  let port = 80
  var client: TCPClient?

  override func viewDidLoad() {
    super.viewDidLoad()
    
    client = TCPClient(address: host, port: Int32(port))
  }
  
  @IBAction func sendButtonAction() {
    guard let client = client else { return }
    
    switch client.connect(timeout: 10) {
    case .success:
      appendToTextField(string: "Connected to host \(client.address)")
      if let response = sendRequest(string: "GET / HTTP/1.0\n\n", using: client) {
        appendToTextField(string: "Response: \(response)")
      }
    case .failure(let error):
      appendToTextField(string: String(describing: error))
    }
  }
  
  private func sendRequest(string: String, using client: TCPClient) -> String? {
    appendToTextField(string: "Sending data ... ")
    
    switch client.send(string: string) {
    case .success:
      return readResponse(from: client)
    case .failure(let error):
      appendToTextField(string: String(describing: error))
      return nil
    }
  }
  
  private func readResponse(from client: TCPClient) -> String? {
    guard let response = client.read(1024*10) else { return nil }
    
    return String(bytes: response, encoding: .utf8)
  }
  
  private func appendToTextField(string: String) {
    print(string)
    textView.text = textView.text.appending("\n\(string)")
  }

}
```

**Comment by danshevluk** [comment]
Hello there! Could you please explain your task?

**Comment by R2D6233** [comment]
Привет, Динис. Я не разрабатываю на Swift. Я больше в робототехнике. Задача состоит в том что робот ждет UDP пакет с командой которую нужно выполнить. Этот пример идеально подходит если бы он был как UDPClient.

**Comment by danshevluk** [comment]
@R2D6233 Это не подходит? https://github.com/swiftsocket/SwiftSocket/blob/master/Sources/UDPClient.swift

**Comment by R2D6233** [comment]
Да, подходит. Только я не знаю как его реализовать(

**Comment by danshevluk** [comment]
@R2D6233 ну судя по всему тебе нужно делать только чтение. Для этого нужно использовать `recv`. Создаешь клиент, потом запускаешь чтение в цикле:
```swift
let host = "...."
let port: Int32 = ...
let client = UDPClient(address: host, port: port)

var shouldReceiveData = true
while shouldReceiveData {
    let (data, _, _) = client.recv(10) // receive 10 bytes
    // do something with the data
}
```

Все это нужно делать в отдельном потоке, чтобы не блокировать исполнение остальной программы. Удачи 🎉

**Comment by R2D6233** [comment]
Огромное спасибо за помощь))

**Comment by SNThunderbolt** [comment]
@danshevluk Hi, I was wondering is there a way to asynchronously read messages of 32 Bytes by UDP recv function?
I wrote the below code but it stuck in an infinite loop:

    func register(username: String) -> (Bool, String) {
        //registering a user
        var udpString : String = "REGISTER:\(username)"

        var output = false
        var result = client.send(string: udpString)
        var response = ""

        if result.isSuccess {
            readingWorkItem1 = DispatchWorkItem {
                guard let item = self.readingWorkItem1 else { return }

                // read incoming msges one at a time and add to message
                while !item.isCancelled {
                    print("hi")
                    let (serverResponse, _, _) = self.client.recv(32)
                    print("this is it \(serverResponse)")
                    if (serverResponse == nil) {
                        print("closing")
                        continue
                    } else {
                        //guard let (d, _, _) = (client.recv(32)) else { continue }
                       // item.cancel()
                        print("hello again")
                        for i in 1...serverResponse!.count {
                            self.newMsg.append(Character(UnicodeScalar(serverResponse![i-1])))
                            print ("The Server Response To {REGISTER} is \(response)")
                            if response == "OK" {
                                output = true
                            } else {
                                output = false
                            }
                        }
                    }
                    print("continusing!")
                }
            }
            DispatchQueue.global().async(execute: readingWorkItem1!)
        } else {
            print ("result unsucessful.")
        }
        client.close()
        return (output, response)
    }
