### ISSUE TITLE
你好想问一下readme 里面讲的拖两个文件进去project是指的udp或者tcp的两个吗，另外一个ysocket.swift需要吗？谢谢！

### ISSUE THREAD

**Issue by samlamgithub** [swiftsocket/SwiftSocket#8]
你好想问一下readme 里面讲的拖两个文件进去project是指的udp或者tcp的两个吗，另外一个ysocket.swift需要吗？谢谢！

**Comment by xyyc** [comment]
@samlamgithub 最简单的是拖入ysocket文件夹。如果只需要tcp就拖入ysocket.swift，ytcpsocket.c
，ytcpsocket.swift,只需要udp就ysocket.swift，yudpsocket.c
，yudpsocket.swift,
