### ISSUE TITLE
TCP Server如何判断客户端是否断开连接？

### ISSUE THREAD

**Issue by lou-lan** [swiftsocket/SwiftSocket#85]
请问TCP Server下如何判断客户端是否断开连接？

**Comment by danshevluk** [comment]
Hello there! Can you rewrite it in english please?

**Comment by lou-lan** [comment]
I created a TCP Server, After TCP Client Debugging tools connection，But I can't detect his disconnection.
Sorry,English is not very fluent, Thanks.

**Comment by danshevluk** [comment]
You cannot handle handle disconnection with `SwiftSocket`. You should implement it somehow yourself or choose another library.

**Comment by lou-lan** [comment]
👍 Thanks!
